#!/bin/sh

# This script fixes the keystore path in the Android.csproj to be relative to the solution root.
# It changes <AndroidSigningKeyStore>android.keystore</AndroidSigningKeyStore> to <AndroidSigningKeyStore>../../android.keystore</AndroidSigningKeyStore>
# Why: The path in csproj is relative to the project directory (src/MyDesktopApplication.Android/), 
# but the keystore is in the root (as generated by previous script and decoded in CI).
# This ensures local and CI builds find the file without moving it.
# No regression: CI decodes to root; relative path from subdir points to root.
# After running, for local builds, run: dotnet build src/MyDesktopApplication.Android/MyDesktopApplication.Android.csproj -p:AndroidSigningPassword=android
# (Password is 'android' as set in previous script; change if customized.)

set -e  # Exit on error

csproj="src/MyDesktopApplication.Android/MyDesktopApplication.Android.csproj"

# Update the path
sed -i 's|<AndroidSigningKeyStore>android.keystore</AndroidSigningKeyStore>|<AndroidSigningKeyStore>../../android.keystore</AndroidSigningKeyStore>|' "$csproj"

echo "Updated keystore path in $csproj to ../../android.keystore"
echo "Fix complete. Run 'dotnet clean; dotnet build src/MyDesktopApplication.Android/MyDesktopApplication.Android.csproj -p:AndroidSigningPassword=android' to verify."
echo "For full solution build, pass the prop to the solution build command."

