using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MyDesktopApplication.Core.Entities;
using MyDesktopApplication.Core.Interfaces;
using MyDesktopApplication.Shared.Data;

namespace MyDesktopApplication.Desktop.ViewModels;

public partial class MainWindowViewModel : ViewModelBase
{
    private readonly IGameStateRepository? _gameStateRepository;
    private GameState _gameState = new();
    private readonly Random _random = new();

    // =========================================================================
    // Observable Properties (backing fields auto-generated by CommunityToolkit)
    // =========================================================================

    [ObservableProperty] private string _greeting = "Welcome to Country Quiz!";
    [ObservableProperty] private int _currentScore;
    [ObservableProperty] private int _highScore;
    [ObservableProperty] private int _currentStreak;
    [ObservableProperty] private int _bestStreak;
    [ObservableProperty] private string _questionText = "Which country has higher...";
    [ObservableProperty] private string _feedbackMessage = "";
    [ObservableProperty] private bool _showFeedback;
    [ObservableProperty] private QuestionType _selectedQuestionType = QuestionType.Population;

    // The two countries being compared
    [ObservableProperty] private Country? _country1;
    [ObservableProperty] private Country? _country2;

    // Has the user answered the current question?
    [ObservableProperty] private bool _hasAnswered;

    // Result message after answering
    [ObservableProperty] private string _resultMessage = "";

    // Visual feedback for correct/wrong answers
    [ObservableProperty] private bool _isCountry1Correct;
    [ObservableProperty] private bool _isCountry1Wrong;
    [ObservableProperty] private bool _isCountry2Correct;
    [ObservableProperty] private bool _isCountry2Wrong;

    // Formatted values shown after answering
    [ObservableProperty] private string _country1Value = "";
    [ObservableProperty] private string _country2Value = "";

    // =========================================================================
    // Computed Properties for UI Binding
    // =========================================================================

    public string ScoreText => $"Score: {CurrentScore}";
    public string StreakText => $"Streak: {CurrentStreak}";
    public string BestStreakText => $"Best: {BestStreak}";
    public string AccuracyText => _gameState.TotalAnswered > 0
        ? $"Accuracy: {_gameState.AccuracyPercentage:F1}%"
        : "Accuracy: --";

    // Question type dropdown options
    public ObservableCollection<QuestionType> QuestionTypes { get; } =
        new(Enum.GetValues<QuestionType>());

    // =========================================================================
    // Constructors
    // =========================================================================

    public MainWindowViewModel()
    {
        // Design-time / parameterless constructor
        GenerateNewQuestion();
    }

    public MainWindowViewModel(IGameStateRepository gameStateRepository)
    {
        _gameStateRepository = gameStateRepository;
    }

    // =========================================================================
    // Initialization
    // =========================================================================

    public async Task InitializeAsync()
    {
        if (_gameStateRepository != null)
        {
            _gameState = await _gameStateRepository.GetOrCreateAsync("default");
            UpdateScoresFromGameState();
        }
        GenerateNewQuestion();
    }

    private void UpdateScoresFromGameState()
    {
        CurrentScore = _gameState.CurrentScore;
        HighScore = _gameState.HighScore;
        CurrentStreak = _gameState.CurrentStreak;
        BestStreak = _gameState.BestStreak;

        OnPropertyChanged(nameof(ScoreText));
        OnPropertyChanged(nameof(StreakText));
        OnPropertyChanged(nameof(BestStreakText));
        OnPropertyChanged(nameof(AccuracyText));
    }

    // =========================================================================
    // Commands
    // =========================================================================

    [RelayCommand]
    private void GenerateNewQuestion()
    {
        var countries = CountryData.GetAllCountries();

        var indices = Enumerable.Range(0, countries.Count)
            .OrderBy(_ => _random.Next())
            .Take(2)
            .ToList();

        Country1 = countries[indices[0]];
        Country2 = countries[indices[1]];

        QuestionText = $"Which country has higher {SelectedQuestionType.GetLabel()}?";

        // Reset answer state
        HasAnswered = false;
        ResultMessage = "";
        IsCountry1Correct = false;
        IsCountry1Wrong = false;
        IsCountry2Correct = false;
        IsCountry2Wrong = false;
        Country1Value = "";
        Country2Value = "";
    }

    [RelayCommand]
    private async Task SelectCountry(string countryParam)
    {
        if (Country1 == null || Country2 == null || HasAnswered) return;

        bool selectedCountry1 = countryParam == "1";

        var val1 = SelectedQuestionType.GetValue(Country1);
        var val2 = SelectedQuestionType.GetValue(Country2);

        bool country1IsHigher = val1 >= val2;
        bool isCorrect = selectedCountry1 == country1IsHigher;

        // Record the answer
        _gameState.RecordAnswer(isCorrect);
        UpdateScoresFromGameState();

        if (_gameStateRepository != null)
        {
            await _gameStateRepository.UpdateAsync(_gameState);
        }

        // Update UI state
        HasAnswered = true;
        Country1Value = SelectedQuestionType.FormatValue(val1);
        Country2Value = SelectedQuestionType.FormatValue(val2);

        // Set visual feedback
        if (country1IsHigher)
        {
            IsCountry1Correct = true;
            IsCountry2Wrong = !isCorrect && !selectedCountry1;
        }
        else
        {
            IsCountry2Correct = true;
            IsCountry1Wrong = !isCorrect && selectedCountry1;
        }

        // Set result message
        ResultMessage = isCorrect
            ? GetCorrectMessage()
            : GetIncorrectMessage();
    }

    [RelayCommand]
    private void NextRound()
    {
        GenerateNewQuestion();
    }

    [RelayCommand]
    private async Task ResetGame()
    {
        _gameState.Reset();
        UpdateScoresFromGameState();

        if (_gameStateRepository != null)
        {
            await _gameStateRepository.UpdateAsync(_gameState);
        }

        GenerateNewQuestion();
    }

    // =========================================================================
    // Helper Methods
    // =========================================================================

    private string GetCorrectMessage()
    {
        if (CurrentStreak >= 10) return "🔥 UNSTOPPABLE! 10+ streak!";
        if (CurrentStreak >= 5) return "🔥 On fire! 5+ streak!";
        if (CurrentStreak >= 3) return "🎯 Nice streak!";
        if (CurrentScore > _gameState.HighScore - 1) return "🏆 NEW HIGH SCORE!";
        return "✅ Correct!";
    }

    private string GetIncorrectMessage()
    {
        if (CurrentStreak == 0 && _gameState.TotalAnswered > 5)
            return "❌ Wrong! Keep trying!";
        return "❌ Wrong!";
    }
}
